version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@34.220.52.96 \
            "echo Start deploy && \
            cd ~/Hacker-News-UI-REACT- && \
            git pull origin master && \
            sudo docker-compose up --build -d && \
            echo Deploy end"
workflows:
  version: 2
  deploy_ec2:
    jobs:
      - build